apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: YOUR_DATASOURCE-app-user-db-secret
  namespace: YOUR_DATASOURCE_NAMESPACE
spec:
  toNamespaces:
    - "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: jupyter-registry-creds
  namespace: YOUR_SESSION_NAMESPACE
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K