apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: YOUR_DATASOURCE-app-user-db-secret
  namespace: YOUR_DATASOURCE_NAMESPACE
spec:
  toNamespaces:
    - "*"
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: YOUR_DATASOURCE-app-user-db-secret
  namespace: YOUR_SESSION_NAMESPACE
spec:
  fromNamespace: YOUR_DATASOURCE_NAMESPACE