---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: mlflow-jupyterhub-hub
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jupyter-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: jupyter-service
          port: 8081
  virtualhost:
    fqdn: jupyter.tanzudatatap.ml