#@ load("@ytt:data", "data")  # for reading data values (generated via ytt's data-values-schema-inspect mode).
#@ load("@ytt:yaml", "yaml")  # for dynamically decoding the output of ytt's data-values-schema-inspect
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "jupyter.tanzu.vmwware.com." + data.values.version
spec:
  refName: jupyter.tanzu.vmwware.com
  version: #@ data.values.version
  releaseNotes: |
    Initial release of the Jupyterhub package
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: #@ "${JUPYTER_REGISTRY_USERNAME}/jupyter-package-content:" + data.values.version
      template:
        - ytt:
            paths:
              - "config/"
        - kbld:
            paths:
              - ".imgpkg/images.yml"
              - "-"
      deploy:
        - kapp: {}