---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jupyter-httpproxy
  namespace: jupyterhub
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: mlflow-jupyterhub-proxy-public
          port: 80 #80
  virtualhost:
    fqdn: jupyter.tanzudatatap.ml