#@data/values
---
singleuser_image_registry: REPLACE_SINGLEUSER_IMAGE_REGISTRY
singleuser_image_repository: REPLACE_SINGLEUSER_IMAGE_REPOSITORY
singleuser_image_tag: REPLACE_SINGLEUSER_IMAGE_TAG
singleuser_image_pullpolicy: REPLACE_SINGLEUSER_IMAGE_PULLPOLICY
singleuser_image_command: REPLACE_SINGLEUSER_IMAGE_COMMAND
singleuser_container_security_context_runasuser: REPLACE_SINGLEUSER_CONTAINER_SECURITY_CONTEXT_RUNASUSER
singleuser_container_security_context_runasgroup: REPLACE_SINGLEUSER_CONTAINER_SECURITY_CONTEXT_RUNASGROUP
singleuser_pod_security_context_runasuser: REPLACE_SINGLEUSER_POD_SECURITY_CONTEXT_RUNASUSER
singleuser_pod_security_context_runasgroup: REPLACE_SINGLEUSER_POD_SECURITY_CONTEXT_RUNASGROUP
proxy_service_public_type: REPLACE_PROXY_SERVICE_PUBLIC_TYPE
proxy_ingress_annotations_ingress_enabled: REPLACE_PROXY_INGRESS_ANNOTATIONS_INGRESS_ENABLED
proxy_service_public_ports_http: REPLACE_PROXY_SERVICE_PUBLIC_PORTS_HTTP
proxy_ingress_annotations_websocket_routes: REPLACE_PROXY_INGRESS_ANNOTATIONS_WEBSOCKET_ROUTES
proxy_ingress_annotations_tls: REPLACE_PROXY_INGRESS_ANNOTATIONS_TLS
proxy_ingress_annotations_self_signed: REPLACE_PROXY_INGRESS_ANNOTATIONS_SELF_SIGNED
