#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jupyterhub-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: proxy-public
          port: 80
  virtualhost:
    fqdn: #@ "jupyter-" + data.values.namespace + "." + data.values.base_domain

