---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: mlops-flux-system
  path: ./clusters/mlops/jupyterhub-accelerator/bitnami-jupyter/4.1.5
  prune: true
  wait: true
  timeout: 10m0s